### ISSUE TITLE
So big of 'pth' file !

### ISSUE THREAD

**Issue by Qidian213** [joe-siyuan-qiao/DetectoRS#1]
emmm

**Comment by joe-siyuan-qiao** [comment]
Hi, yes they are big as DetectoRS is built on multi-stage detector HTC. If the model size is a big issue for your application, you are welcome to incorporate DetectoRS with other light-weighted detectors than HTC as long as they use FPN and 3x3 convolutional layers. I believe DetectoRS will also strongly improve their performances.

By the way, thanks for the feedback that those download links work.

**Comment by lucasjinreal** [comment]
@joe-siyuan-qiao Will u apply detectoRS to some lightweighted detection methods such as some SOTA anchor-free detectos?

**Comment by Qidian213** [comment]
@joe-siyuan-qiao Thanks for your replay !

**Comment by joe-siyuan-qiao** [comment]
@jinfagang Thanks for your suggestions. We haven't done any light-weighted experiments yet but they are on our todo list now. Thanks!
