### ISSUE TITLE
How to train private VOC-alike file format? Please

### ISSUE THREAD

**Issue by GinkgoX** [joe-siyuan-qiao/DetectoRS#11]
Dear auther:
       When I get started the project, I encounter the problem about VOC format training.Could you give me some suggestion abuot this, thanks a lot.

Sincerely

**Comment by joe-siyuan-qiao** [comment]
Hi, thanks for your interest. Please take a look at the original mmdetection repo to see if there is more documentation about training models with VOC format. Please also stay tuned as we are moving the current codebase to mmdetection v2.0 to support more detectors in addition to HTC, which might make training on VOC easier.

**Comment by GinkgoX** [comment]
Thanks for your patient help, I still fell puzzled about this project: Can we train our data without mask(only bbox) info even we covert the voc-alike to coco-alike bounding box?

**Comment by joe-siyuan-qiao** [comment]
DetectoRS currently is built on HTC, which requires many other inputs than bounding box. After we transfer it to mmdetection v2.0, bbox-only detectors will be supported. Please stay tuned.

**Comment by GinkgoX** [comment]
well, sincerely thanks for your help.



---Original---
