### ISSUE TITLE
The purpose of the Post-Global Context

### ISSUE THREAD

**Issue by Alien1007** [joe-siyuan-qiao/DetectoRS#12]
I have just read your paper. It's an excellent work. However, I am confused about the purpose of the Post-Global Context. It is written in the paper that _We then move the global information outside the switch function and place it before and after the major body so that both Conv and S can benefit from it_. But it seems that only the Pre-Global Context is injected to _Conv_ and _S_. How can I understand those words correctly?

**Comment by joe-siyuan-qiao** [comment]
Hi, thanks for your question. Originally, we only had a global context module before the main body. Then, we ran experiments and found out that putting it after the main body also helped. So in the current version, we have two of them, one in the front and one in the back.

**Comment by Alien1007** [comment]
I got it. Thanks for your reply!
