### ISSUE TITLE
请问一下，为什么我用作者off-the-shelf的模型测试，效果要比post的差一些？

### ISSUE THREAD

**Issue by ignitemylife** [joe-siyuan-qiao/DetectoRS#15]
DetectoRS_R50-0f1c8080.pth     bbox: 51.1  segm: 44.0
DetectoRS_X101-ed983634.pth  bbox: 52.9  segm: 45.3

环境： 
pytorch1.4 
cuda: 10.0 
cudnn: 7.6.5
mmcv: 0.5.9
pycocotools: 2.0 PyPi

**Comment by panjianning** [comment]
> DetectoRS_R50-0f1c8080.pth bbox: 51.1 segm: 44.0
> DetectoRS_X101-ed983634.pth bbox: 52.9 segm: 45.3
> 
> 环境：
> pytorch1.4
> cuda: 10.0
> cudnn: 7.6.5
> mmcv: 0.5.9
> pycocotools: 2.0 PyPi

I guess you get this score on COCO dev,  which is often lower than the score on COCO test-dev.

**Comment by joe-siyuan-qiao** [comment]
@ignitemylife What you reported match the val2017 AP on our side. @PanJianning thanks for your help.

**Comment by ignitemylife** [comment]
Got it, really thank u for your help @joe-siyuan-qiao @PanJianning
