### ISSUE TITLE
Training problem of own dataset

### ISSUE THREAD

**Issue by xioayezi6555** [joe-siyuan-qiao/DetectoRS#18]
Hello!            
Can you give a more detailed training data set steps.. (either coco format or VOC format can be used)

**Comment by joe-siyuan-qiao** [comment]
Hi, please take a look at the documentation that mmdetection provides regarding how to use custom datasets in GETTING_STARTED.md.

**Comment by sporterman** [comment]
@joe-siyuan-qiao hello  ， I can't get seg_prefix data in coco format data in  DetectoRS_mstrain_400_1200_x101_32x4d_40e.py,  what it is??    how to get this kind of data?

**Comment by sporterman** [comment]
my data was labeled by labelme, and then convert to coco format by labelme2coco.py,   but just get annotations.json and JPEGImages,   only jpg data in JPEGImages,  but the seg_prefix point to this path and need png format data, how to get them?

**Comment by joe-siyuan-qiao** [comment]
Duplicate of #19.
