### ISSUE TITLE
question about DetectoRS_mstrain_400_1200_x101_32x4d_40e.py?

### ISSUE THREAD

**Issue by sporterman** [joe-siyuan-qiao/DetectoRS#19]
line 269, seg_prefix,  point to stuffthing,    but this dataset is for senmantic segmantation, not instance.
the train setting include instance_trianval2017.json and stuffthing(for senmantic segmantation), why??

**Comment by sporterman** [comment]
@joe-siyuan-qiao

**Comment by joe-siyuan-qiao** [comment]
Hi, please take a look at https://github.com/joe-siyuan-qiao/DetectoRS/tree/master/configs/htc for preparing the dataset.
