### ISSUE TITLE
Can you provide the model file of reaching 54.7AP mentioned in the paper?

### ISSUE THREAD

**Issue by Iceland-Leo** [joe-siyuan-qiao/DetectoRS#2]
Can you provide the model file of reaching 54.7AP mentioned in the paper?

**Comment by gufanyuanying0852** [comment]
> Can you provide the model file of reaching 54.7AP mentioned in the paper?

54.7AP need use test-time augmentation. It seems to be said in the paper

**Comment by Iceland-Leo** [comment]
OK. Thank you!



发自我的iPhone


------------------ Original ------------------

**Comment by joe-siyuan-qiao** [comment]
54.7AP is achieved by the provided ResNeXt-101-32x4d model with test-time augmentation. @Iceland-Leo thanks for the question and @gufanyuanying0852 thanks for your help.

**Comment by Smalltarget108** [comment]
> 54.7AP is achieved by the provided ResNeXt-101-32x4d model with test-time augmentation. @Iceland-Leo thanks for the question and @gufanyuanying0852 thanks for your help.
Hello, Very nice work.could you tell me how to perform test time augmentation at mmdetection-v1 code(master branch) base?Thank you
