### ISSUE TITLE
Install question

### ISSUE THREAD

**Issue by ChaseTuring** [joe-siyuan-qiao/DetectoRS#21]
I install DetectoRS following mmdetection install.md.And then when I run DetecoRS/tools/train.py use DetectoRS_mstrain_400_1200_x101_32x4d_40e.py, "KeyError: 'RecursiveFeaturePyramid is not in the detector registry'"occured. So if I have some mistake during install DetectoRS? And I should clone mmdetection or DetecoRS and then run pip install -v -e .?

**Comment by D0ub1ePieR** [comment]
i meet the same problem. i clone DetectoRS and run pip install -v -e . ,but it can't be installed successfully. How did you solve it? Thanks.

**Comment by ChaseTuring** [comment]
Hi, sorry to reply you so late.
I clone DetectoRS. I solve the problem just by install torchvision==0.5.0 and then install torch==1.4.0.After that I run pip install -v -e. .Finally it work.
But I don't sure it will solve your problem, you can just try it.










At 2020-06-15 19:09:23, "D0ub1ePieR" <notifications@github.com> wrote:

i meet the same problem. i clone DetectoRS and run pip install -v -e . ,but it can't be installed successfully. How did you solve it? Thanks.

**Comment by D0ub1ePieR** [comment]
Thank you for your help. I create a new conda env and then follow your steps.It works.
Before that, i clone DetectoRS in the old env.  : )
