### ISSUE TITLE
Question about the whole model size with rfp_sharing=False

### ISSUE THREAD

**Issue by ZhongYingMatrix** [joe-siyuan-qiao/DetectoRS#22]
Thanks for your awesome work! 
Sorry for disturbing you. I notice that another new backbone would be builten while rfp_sharing is set as 'False'.
https://github.com/joe-siyuan-qiao/DetectoRS/blob/84bd7232a541462511afacdc028fc5a8ba94dce0/mmdet/models/detectors/rfp.py#L79-L85
Would it cost extra memo for a whole ResNet backbone while training, inferencing or ckpt saving?
Hope for ur reply~

**Comment by joe-siyuan-qiao** [comment]
Yes, when rfp_sharing is set to False, everything regarding the cost of backbone will be approximately doubled.

**Comment by ZhongYingMatrix** [comment]
Thx for reply~!
