### ISSUE TITLE
time consuming?

### ISSUE THREAD

**Issue by AndyYuan96** [joe-siyuan-qiao/DetectoRS#24]
Why two times backbone, and the time consuming is not bigger than HTC too much?  and two times backbone is sequential.

**Comment by joe-siyuan-qiao** [comment]
Hi, the reason is that multi-stage detectors typically have more computations after their backbones done extracting features.

**Comment by AndyYuan96** [comment]
OK, thank you, I'm not familar with multi-stage detectors.
