### ISSUE TITLE
The speed may be wrongly reported in your paper.

### ISSUE THREAD

**Issue by PKUbahuangliuhe** [joe-siyuan-qiao/DetectoRS#28]
your method runs backbone twice, so the speed will be slowed down obviously

**Comment by ZhongYingMatrix** [comment]
HTC spends lots of time on cascade head.

**Comment by joe-siyuan-qiao** [comment]
@PKUbahuangliuhe Thanks for the question. The impact on the speed depends on the workload after the backbone done extracting the features. HTC does many things after that, so the speed impact isn't that strong. @ZhongYingMatrix Thanks for your help.
