### ISSUE TITLE
about batch size

### ISSUE THREAD

**Issue by SpicyChicken4L** [joe-siyuan-qiao/DetectoRS#29]
I'm reproducing the performance using this repo but I didn't reproduce the reported resnet50 51.3 Box AP. I guess my batch size setting is wrong. I use LR 0.02, 1 image per gpu and 32 GPUs for resnet50, and I got 50.4 Box AP.
May I ask the image per GPU and GPU number for resnet50 and resnext101-32x4d?
thank you.

**Comment by joe-siyuan-qiao** [comment]
Hi, please take a look at the learning schedule/batch size here

https://github.com/joe-siyuan-qiao/DetectoRS/tree/master/configs/htc

In your case, you might want to change the base learning rate to 0.04 to use 32 images/batch. But I'm not sure how that will affect APs.
