### ISSUE TITLE
typo in paper

### ISSUE THREAD

**Issue by zehuichen123** [joe-siyuan-qiao/DetectoRS#3]
section 5.1 experimental details, for 1x schedule, lr multiplied by 0.1 after 8 and 12 epochs. Maybe 12 should be 11?
Another question, does DetectoRS adopts softnms and multiscale training in the main result to reach mAP53.3? I noticed that you mentioned it in section 5.1 but didn't annotate it table 4.
ps. figure1b is so cute :)

**Comment by joe-siyuan-qiao** [comment]
Yes, it should be 11. Thanks for pointing that out!

Yes, multi-scale training is used for DetectoRS in Tab. 4. SoftNMS is used for ResNeXt-101-32x4d only and improves ~0.5 box AP. You can see the config files to find out the training and testing settings. We use them to get the reported numbers.

We just found that octopuses are very good for illustrating convolutions as they have 8 arms which look similar to the weight layout in 3x3 convs. And they are cute.

**Comment by zehuichen123** [comment]
Thanks for your reply!
