### ISSUE TITLE
Where can i find switchable dilated conv blocks and also the feedback operation for backbone , im trying to develop detectoRS from scratch in TF2.x

### ISSUE THREAD

**Issue by kartik4949** [joe-siyuan-qiao/DetectoRS#35]

**Comment by RohitKeshari** [comment]
I am interested.

**Comment by joe-siyuan-qiao** [comment]
Hi, please see the commit history to find out what files have been modified.

**Comment by kartik4949** [comment]
Thanks for the comment , i found it!

**Comment by kartik4949** [comment]
> I am interested.

Hi if you want to contrib in tf 2.x conversion , mail me kartik4949@gmail.com
