### ISSUE TITLE
loss nan occurred when i integrated sac module into atss detector

### ISSUE THREAD

**Issue by zyf12389** [joe-siyuan-qiao/DetectoRS#37]
Thanks for your excellent work.
In addition to the dataset, the configuration of atss is the same as that in mmdetection. I used SAC module in res101, and only using res101 can be trained normally. Lowering the lr doesn't work. I can't figure out why nan appeared.

**Comment by joe-siyuan-qiao** [comment]
I trained atss + rn101 + sac with mmdetv2 branch for 1 epoch, and everything looked normal to me. You can find the log here

http://cs.jhu.edu/~syqiao/DetectoRS/atss_r101_sac.zip

which also includes the config file.

**Comment by shiontao** [comment]
maybe due to the fp16
