### ISSUE TITLE
what's the performance on Cascade R-CNN?

### ISSUE THREAD

**Issue by greathope** [joe-siyuan-qiao/DetectoRS#4]
hi, thank you for your impressive work!
Did you try your RFP and SAC on vanilla object detection model like Cascade R-CNN? what's the performance? thank you in advance.

**Comment by roadcode** [comment]
also concern the result on cascade r-cnn, cause there is only box annotation in my dataset

**Comment by joe-siyuan-qiao** [comment]
Thanks for your question. Unfortunately, we haven't done any experiments trying to incorporate them with Cascade R-CNN, but we do have plans to do so. I'll close this issue for now and may reopen it once we have some results to show. Thanks again.
