### ISSUE TITLE
Can I frozen the first stage of resnet50 when train the model with pretrained backbone?

### ISSUE THREAD

**Issue by XianYuZhiWang** [joe-siyuan-qiao/DetectoRS#41]
Thanks for the nice job！
when I load pretrained resnet50 backbone weights, there are many missing keys, so I wonder , can I frozen the first stage of resnet50 when I training with pretrained backbone?

**Comment by joe-siyuan-qiao** [comment]
Thanks for the question. Observing missing keys is normal as they will be trained on COCO. I think the first stage is frozen by default in the config files.
