### ISSUE TITLE
in build resnet rfp

### ISSUE THREAD

**Issue by sunpeng96** [joe-siyuan-qiao/DetectoRS#43]
Thanks for your error report and we appreciate it a lot.

in resnet.py 305
out = out + rfp_feat

The size of 'out' and 'rfp_feat' is not match

**Comment by joe-siyuan-qiao** [comment]
Thanks for reporting this. Have you made any modifications to the configuration files or code?

**Comment by sunpeng96** [comment]
Hi, Due to the busy work in the previous period, there was no timely reply. Debugging the program today, the problem still exists. Through debugging, I found that the problem lies in resnet.py lines of 607  RFP_ forward(). x = layer.rfp_ forward(x, rfp_ In feat), layer does not operate on img, resulting in x is tensor(img) in this statement. Finally, in the RFP_ In forward (), out = out + RFP_ Results of feat

**Comment by sunpeng96** [comment]
In fact, I didn't make any changes to the program.
