### ISSUE TITLE
The vision of mmcv seems not match 

### ISSUE THREAD

**Issue by Liu199604** [joe-siyuan-qiao/DetectoRS#44]
When I run test.py, it reports the error: "KeyError: 'RecursiveFeaturePyramid is not in the detector registry'
", so could help me about this? Thank you very much.

**Comment by joe-siyuan-qiao** [comment]
Hi, it seems you installed mmdetection instead of this repo. But DetectoRS is officially supported by mmdetection, so now it should be fine in either case.

**Comment by Liu199604** [comment]
> Hi, it seems you installed mmdetection instead of this repo. But DetectoRS is officially supported by mmdetection, so now it should be fine in either case.

Thank you very much, I will try it again.
