### ISSUE TITLE
torch version update in requirements

### ISSUE THREAD

**Issue by xizero00** [joe-siyuan-qiao/DetectoRS#6]
Hi,
Could you please update the requirements in the requirements directory
Your mmdetection codebase supports torch>=1.1.0,<=1.4.0
and torchvision==0.5.0
This problem is mentioned in issue#5
Related files:
```
requirements/build.txt
requirements/runtime.txt
```

**Comment by joe-siyuan-qiao** [comment]
Big thanks for your suggestion! We've added the version requirements. Thanks!
