### ISSUE TITLE
just object detect

### ISSUE THREAD

**Issue by missbook520** [joe-siyuan-qiao/DetectoRS#7]
Thanks for your great work!
If I just want to use object detection and no mask ,how can I adjust the config?
Thanks!

**Comment by CarryHJR** [comment]
i meet the same situation too, i wanna get the config of only detection

**Comment by kiddliao** [comment]
> i meet the same situation too, i wanna get the config of only detection

me too

**Comment by joe-siyuan-qiao** [comment]
Thanks for your interest in using DetectoRS. Currently, it only supports HTC, so it needs every data input of HTC to train and test it. However, we are currently refactoring the codebase and move it to mmdet v2.0, where we will support as many base detectors as possible. Please stay tuned. Thanks!

**Comment by CarryHJR** [comment]
i use bbox as segmentation, and delete seg head, it works, the mAP looks not bad

**Comment by yuyijie1995** [comment]
@CarryHJR can you share your changed code? I met the same  problem.
